# Generated by Django 4.2.30 on 2026-06-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('service', models.CharField(choices=[('menage', 'Ménage / Repassage'), ('seniors', 'Accompagnement / Aide aux seniors'), ('enfants', "Garde d'enfants"), ('jardinage', 'Jardinage / Bricolage'), ('autre', 'Autre besoin')], default='autre', max_length=50, verbose_name='Prestation souhaitée')),
                ('message', models.TextField(verbose_name='Message / Description des besoins')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
            ],
            options={
                'verbose_name': 'Message de Contact',
                'verbose_name_plural': 'Messages de Contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
